#pragma once

inline constexpr char kRemotePage[] = R"HTML(<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<title>Waveform One · Now playing</title><style>
:root{color-scheme:dark;font-family:Arial,sans-serif;--bg:#090e0a;--panel:#141c15;--line:#354638;--ink:#edf3e8;--muted:#a0afa1;--green:#a8d57a;--lavender:#a79ae8}
*{box-sizing:border-box}[hidden]{display:none!important}body{margin:0;background:var(--bg);color:var(--ink);min-height:100svh;padding:env(safe-area-inset-top) 22px env(safe-area-inset-bottom)}
button,input{font:inherit}button{min-height:48px;border:1px solid var(--line);border-radius:12px;background:var(--panel);color:var(--ink);padding:10px 16px;cursor:pointer}button:disabled{opacity:.5;cursor:default}button:focus-visible,input:focus-visible{outline:2px solid var(--lavender);outline-offset:4px}
header{max-width:900px;margin:auto;min-height:84px;display:flex;align-items:center;justify-content:space-between;gap:12px}.brand{font-size:12px;letter-spacing:2px;color:var(--green);font-weight:bold}.settings-button{background:transparent;font-size:14px}
main{max-width:900px;margin:18px auto 40px}.player{display:grid;grid-template-columns:minmax(0,1fr);gap:28px}.cover{position:relative;aspect-ratio:1;overflow:hidden;border:2px solid var(--line);border-radius:20px;background:radial-gradient(ellipse at 30% 15%,#263528,#111812 75%);display:grid;place-items:center}.cover.known{border-color:var(--green)}.cover.searching:not(.known){border-color:var(--lavender)}
.cover img{position:absolute;width:100%;height:100%;object-fit:cover}.placeholder{text-align:center;color:var(--muted);font-size:clamp(34px,9vw,64px);letter-spacing:1px;line-height:1.2}.wave{display:flex;justify-content:center;align-items:center;gap:7px;height:50px;margin-top:26px}.wave i{display:block;width:7px;height:12px;border-radius:8px;background:var(--lavender);animation:wave 1.3s ease-in-out infinite alternate;animation-delay:calc(var(--i)*-.12s)}@keyframes wave{to{height:48px;opacity:.4}}
.eyebrow{margin:0 0 14px;color:var(--green);font-size:16px;letter-spacing:3px;font-weight:bold}h1{font-size:clamp(30px,7vw,48px);font-weight:500;line-height:1.14;margin:0 0 16px;overflow-wrap:anywhere}.artist{font-size:23px;line-height:1.35;margin:0 0 8px;overflow-wrap:anywhere}.album{font-size:17px;color:var(--muted);line-height:1.5;margin:0;overflow-wrap:anywhere}.activity{color:var(--muted);font-size:14px;margin:24px 0 0;min-height:20px}.dot{display:inline-block;background:var(--green);width:6px;height:6px;border-radius:50%;margin-right:8px}.activity.searching .dot{background:var(--lavender)}
.connection{font-size:13px;color:var(--muted);margin:24px 0 0;line-height:1.5}.connection:empty{display:none}.overlay{position:fixed;inset:0;background:#0009;z-index:2;display:grid;place-items:center;padding:20px}.sheet{width:100%;max-width:520px;max-height:calc(100svh - 40px);overflow:auto;background:var(--panel);border:1px solid var(--line);border-radius:22px;padding:24px}.sheet-heading{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:24px}.sheet-heading h2{font-size:28px;margin:0}.section{border-top:1px solid var(--line);padding:24px 0 0;margin:24px 0 0}.section h3{font-size:13px;letter-spacing:2px;color:var(--green);margin:0 0 16px}.styles{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px}.styles button{padding:10px 4px;font-size:14px}.styles button[aria-pressed=true]{border-color:var(--green);color:var(--green)}label{display:block;font-size:15px;color:var(--muted)}input[type=text]{width:100%;margin:10px 0 12px;padding:13px;border:1px solid var(--line);border-radius:9px;background:var(--bg);color:var(--ink);font-size:18px}input[type=range]{width:100%;height:44px;accent-color:var(--green)}.save{width:100%}.feedback{font-size:14px;color:var(--green);min-height:20px;margin:20px 0 0;line-height:1.5}
@media(min-width:700px){main{margin-top:44px}.player{grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:42px;align-items:center}.eyebrow{font-size:20px}.connection{margin-top:32px}}
@media(prefers-reduced-motion:reduce){.wave i{animation:none;height:28px}}
</style></head><body>
<header><span class="brand">WAVEFORM ONE</span><button class="settings-button" id="open-settings" aria-controls="settings" aria-expanded="false">Settings</button></header>
<main><div class="player"><div class="cover" id="cover"><div class="placeholder" id="placeholder">WAVEFORM<br>ONE<div class="wave" id="wave" hidden aria-hidden="true"><i style="--i:0"></i><i style="--i:1"></i><i style="--i:2"></i><i style="--i:3"></i><i style="--i:4"></i><i style="--i:5"></i><i style="--i:6"></i><i style="--i:7"></i><i style="--i:8"></i></div></div><img id="artwork" alt="" hidden referrerpolicy="no-referrer"></div>
<div class="metadata"><p class="eyebrow" id="eyebrow">YOUR MUSIC</p><h1 id="title">Connecting…</h1><p class="artist" id="artist"></p><p class="album" id="album"></p><p class="activity" id="activity"><span class="dot"></span><span id="activity-text">Connecting to Waveform One</span></p></div></div><p class="connection" id="connection" role="status"></p></main>
<div class="overlay" id="settings" hidden><section class="sheet" role="dialog" aria-modal="true" aria-labelledby="settings-title"><div class="sheet-heading"><h2 id="settings-title">Settings</h2><button id="close-settings">Done</button></div>
<fieldset id="controls" disabled style="border:0;padding:0;margin:0;min-width:0"><label for="name">Your name</label><input id="name" type="text" maxlength="40" autocomplete="given-name"><button class="save" id="save-name">Save name</button>
<div class="section"><h3>LED STYLE</h3><div class="styles"><button data-style="classic" aria-pressed="false">Classic</button><button data-style="mirrored" aria-pressed="false">Mirrored</button><button data-style="waterfall" aria-pressed="false">Waterfall</button></div></div>
<div class="section"><h3>DISPLAY</h3><label for="brightness">Brightness <output id="brightness-value">100%</output></label><input id="brightness" type="range" min="10" max="100" value="100"></div></fieldset><p class="feedback" id="feedback" role="status"></p></section></div>
<script>
const $=id=>document.getElementById(id);
let csrf='',pollTimer,artworkUrl='',requestActive=false,settingsOpen=false,failures=0;
function pairedMessage(){return 'Scan the QR code on Waveform One to connect.'}
function loseSession(){csrf='';$('controls').disabled=true;$('connection').textContent=pairedMessage();$('feedback').textContent=pairedMessage();$('activity-text').textContent='Connection required'}
function showSettings(open){settingsOpen=open;$('settings').hidden=!open;$('open-settings').setAttribute('aria-expanded',String(open));document.body.style.overflow=open?'hidden':'';(open?$('close-settings'):$('open-settings')).focus()}
$('open-settings').onclick=()=>showSettings(true);$('close-settings').onclick=()=>showSettings(false);
$('settings').onclick=e=>{if(e.target===$('settings'))showSettings(false)};
document.addEventListener('keydown',e=>{if(!settingsOpen)return;if(e.key==='Escape')showSettings(false);if(e.key==='Tab'){const nodes=[...$('settings').querySelectorAll('button,input')].filter(n=>!n.disabled&&!n.closest('fieldset[disabled]'));const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});
function showPlaceholder(){$('artwork').hidden=true;$('placeholder').hidden=false}
$('artwork').onload=()=>{$('artwork').hidden=false;$('placeholder').hidden=true};$('artwork').onerror=showPlaceholder;
function render(state){const track=state.track,searching=['capturing','identifying'].includes(state.status);$('cover').classList.toggle('known',!!track);$('cover').classList.toggle('searching',searching);$('activity').classList.toggle('searching',searching);$('wave').hidden=!searching;
 $('eyebrow').textContent=track?'NOW PLAYING':'YOUR MUSIC';$('title').textContent=track?track.title:'Listening for music';$('artist').textContent=track?track.artist:'';$('album').textContent=track?track.album:'';
 $('activity-text').textContent=searching?(track?'Checking what’s playing…':'Finding your song…'):state.status==='unavailable'?'Trying again shortly':track?'Enjoy the music':'Play a song to get started';
 const url=track&&track.artwork||'';if(url!==artworkUrl){artworkUrl=url;showPlaceholder();if(url){$('artwork').alt=track.album?track.album+' album artwork':'Album artwork';$('artwork').src=url}else{$('artwork').removeAttribute('src');$('artwork').alt=''}}
 if(!settingsOpen){$('name').value=state.name;$('brightness').value=state.brightness;$('brightness-value').textContent=state.brightness+'%'}
 document.querySelectorAll('[data-style]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.style===state.style)));
}
async function post(path,data){if(!csrf){loseSession();return false}try{const response=await fetch(path,{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/x-www-form-urlencoded','X-Waveform-CSRF':csrf},body:new URLSearchParams(data)});if(response.status===403){loseSession();return false}if(!response.ok)throw Error();$('feedback').textContent=path==='/api/style'?'Applying LED style…':'Saved';return true}catch{$('feedback').textContent='Could not save. Please try again.';return false}}
$('save-name').onclick=()=>{const name=$('name').value.trim();if(name)post('/api/name',{name});else $('feedback').textContent='Enter your name first.'};document.querySelectorAll('[data-style]').forEach(button=>button.onclick=()=>post('/api/style',{style:button.dataset.style}));
// Commit a slider change once; dragging never creates overlapping device requests.
$('brightness').oninput=()=>{$('brightness-value').textContent=$('brightness').value+'%'};$('brightness').onchange=()=>post('/api/brightness',{value:$('brightness').value});
async function poll(){clearTimeout(pollTimer);if(requestActive||document.hidden||!csrf)return;requestActive=true;try{const response=await fetch('/api/state',{credentials:'same-origin',cache:'no-store',signal:AbortSignal.timeout(8000)});if(response.status===401){loseSession();return}if(!response.ok)throw Error();render(await response.json());failures=0;$('connection').textContent=''}catch{failures++;$('connection').textContent='Reconnecting to Waveform One…'}finally{requestActive=false;if(csrf&&!document.hidden)pollTimer=setTimeout(poll,Math.min(10000,2000*(failures+1)))}}
document.addEventListener('visibilitychange',()=>{if(!document.hidden)poll();else clearTimeout(pollTimer)});
async function connect(){try{const response=await fetch('/api/session',{credentials:'same-origin',cache:'no-store',signal:AbortSignal.timeout(8000)});if(!response.ok)throw Error();csrf=await response.text();$('controls').disabled=false;poll();post('/api/time',{epoch:Math.floor(Date.now()/1000)})}catch{$('title').textContent='Welcome to Waveform One';loseSession()}}connect();
</script></body></html>)HTML";
